package cl.restaurante.api.health;

import java.util.Base64;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.mock.web.MockHttpSession;
import org.springframework.mock.web.MockMultipartFile;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.web.context.WebApplicationContext;
import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

// H2 aislado: nunca usa las credenciales ni la base de Oracle Cloud.
@SpringBootTest(properties={"spring.datasource.url=jdbc:h2:mem:permissions;MODE=Oracle;DB_CLOSE_DELAY=-1",
    "spring.datasource.driver-class-name=org.h2.Driver","spring.datasource.username=sa","spring.datasource.password=",
    "spring.profiles.active=test","marigex.jobs.enabled=false"})
class PermissionsIntegrationTest {
    @Autowired WebApplicationContext context;
    @org.springframework.test.context.bean.override.mockito.MockitoSpyBean JdbcTemplate jdbc;
    @org.springframework.test.context.bean.override.mockito.MockitoBean AiScheduleClient ai;
    @Autowired NotificationService notifications;
    @Autowired NotificationPreferences preferences;
    @Autowired NotificationDelivery delivery;

    @org.springframework.test.context.bean.override.mockito.MockitoBean NotificationTransport transport;
    MockMvc mvc;
    MockHttpSession owner, worker, otherWorker, kitchen, salon;
    static final byte[] PNG=Base64.getDecoder().decode("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aM1sAAAAASUVORK5CYII=");
    MockHttpSession session(long id) { var s=new MockHttpSession(); s.setAttribute("userId",id); return s; }
    @BeforeEach void init() throws Exception {
        mvc=MockMvcBuilders.webAppContextSetup(context).build();
        // Destructivo únicamente dentro de la base H2 efímera de ESTA prueba.
        jdbc.execute("DROP ALL OBJECTS");
        jdbc.execute("CREATE TABLE APP_ACTIVIDAD(ID_ACTIVIDAD NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,USUARIO VARCHAR2(160),ACCION VARCHAR2(100),MODULO VARCHAR2(100),DETALLE VARCHAR2(1000),CREADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("CREATE TABLE APP_NOTIFICACION("
        + "ID_NOTIFICACION NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
        + "ID_USUARIO NUMBER,MODULO VARCHAR2(60),MENSAJE VARCHAR2(1000),"
        + "LEIDA CHAR(1) DEFAULT 'N',"
        + "CREADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("CREATE TABLE APP_PROPUESTA_HORARIO(ID_PROPUESTA VARCHAR2(36) PRIMARY KEY,ID_USUARIO NUMBER,FECHA_INICIO DATE,CONTENIDO CLOB,ESTADO VARCHAR2(12) DEFAULT 'BORRADOR',CREADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("CREATE TABLE APP_EMPLEADO(ID_EMPLEADO NUMBER PRIMARY KEY,NOMBRE VARCHAR2(160),CARGO VARCHAR2(80),AREA VARCHAR2(80),ESTADO VARCHAR2(10))");
        jdbc.execute("CREATE TABLE APP_USUARIO(ID_USUARIO NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,ID_EMPLEADO NUMBER UNIQUE,USUARIO VARCHAR2(60) UNIQUE,ROL VARCHAR2(30),ACTIVO CHAR(1),CLAVE_HASH VARCHAR2(300))");
jdbc.execute(
        "CREATE TABLE APP_TAREA_DIARIA (" +
        "ID_TAREA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
        "TAREA VARCHAR2(200), " +
        "RESPONSABLE_ID NUMBER, " +
        "FECHA DATE, " +
        "ESTADO VARCHAR2(30), " +
        "AREA VARCHAR2(80), " +
        "METODO_COMPLETADO VARCHAR2(10) DEFAULT 'FOTO' NOT NULL, " +
        "CONSTRAINT CK_TAREA_METODO CHECK " +
        "(METODO_COMPLETADO IN ('SIMPLE', 'FOTO'))" +
        ")"
);
        jdbc.execute("CREATE TABLE APP_EVIDENCIA_TAREA(ID_EVIDENCIA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,ID_TAREA NUMBER,ID_EMPLEADO NUMBER,NOMBRE_ARCHIVO VARCHAR2(255),TIPO_CONTENIDO VARCHAR2(80),FOTO BLOB,ESTADO VARCHAR2(20) DEFAULT 'ENVIADA',CREADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("CREATE TABLE APP_HORARIO_IMAGEN(ID_HORARIO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,TITULO VARCHAR2(160),NOMBRE_ARCHIVO VARCHAR2(255),TIPO_CONTENIDO VARCHAR2(80),IMAGEN BLOB,CREADO_POR NUMBER,CREADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("CREATE TABLE APP_HORARIO_DESTINATARIO(ID_HORARIO NUMBER,ID_EMPLEADO NUMBER,PRIMARY KEY(ID_HORARIO,ID_EMPLEADO))");
        jdbc.execute("CREATE TABLE APP_PLAZA(ID_PLAZA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,CARGO VARCHAR2(80),AREA VARCHAR2(80),CUPOS NUMBER,ACTIVA CHAR(1))");
        jdbc.execute("CREATE TABLE APP_ASISTENCIA(ID_ASISTENCIA NUMBER PRIMARY KEY,EMPLEADO_ID NUMBER,FECHA DATE,HORA_ENTRADA VARCHAR2(5),HORA_SALIDA VARCHAR2(5),ESTADO VARCHAR2(30))");
        jdbc.execute("CREATE TABLE APP_INCIDENCIA(ID_INCIDENCIA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,TIPO VARCHAR2(80),AREA VARCHAR2(80),DESCRIPCION VARCHAR2(500),RESPONSABLE_ID NUMBER,ESTADO VARCHAR2(30))");
jdbc.execute("CREATE TABLE APP_INSUMO("
        + "ID_INSUMO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
        + "NOMBRE VARCHAR2(100),CATEGORIA VARCHAR2(80),"
        + "STOCK_ACTUAL NUMBER,UNIDAD VARCHAR2(20),"
        + "STOCK_MINIMO NUMBER,STOCK_MAXIMO NUMBER,"
       + "ALERTA_ESTADO VARCHAR2(10) DEFAULT 'NORMAL')");
        jdbc.execute("CREATE TABLE APP_COMPRA(ID_COMPRA NUMBER PRIMARY KEY,ESTADO VARCHAR2(30))");
        jdbc.execute("CREATE TABLE APP_CONTROL_SANITARIO(ID_CONTROL NUMBER PRIMARY KEY,ESTADO VARCHAR2(30))");
        jdbc.execute("CREATE TABLE APP_TURNO(ID_TURNO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,EMPLEADO_ID NUMBER,FECHA DATE,HORA_INICIO VARCHAR2(5),HORA_TERMINO VARCHAR2(5),AREA VARCHAR2(80))");
        jdbc.execute("CREATE TABLE IF NOT EXISTS APP_ASISTENCIA (ID_ASISTENCIA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
        jdbc.execute("ALTER TABLE APP_ASISTENCIA ADD COLUMN IF NOT EXISTS EMPLEADO_ID NUMBER");
        jdbc.execute("ALTER TABLE APP_ASISTENCIA ADD COLUMN IF NOT EXISTS FECHA DATE");
        jdbc.execute("ALTER TABLE APP_ASISTENCIA ADD COLUMN IF NOT EXISTS HORA_ENTRADA VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_ASISTENCIA ADD COLUMN IF NOT EXISTS HORA_SALIDA VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_ASISTENCIA ADD COLUMN IF NOT EXISTS ESTADO VARCHAR2(500)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS APP_COCINA (ID_COCINA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
        jdbc.execute("ALTER TABLE APP_COCINA ADD COLUMN IF NOT EXISTS PREPARACION VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_COCINA ADD COLUMN IF NOT EXISTS RESPONSABLE_ID NUMBER");
        jdbc.execute("ALTER TABLE APP_COCINA ADD COLUMN IF NOT EXISTS HORA VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_COCINA ADD COLUMN IF NOT EXISTS ESTADO VARCHAR2(500)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS APP_COMPRA (ID_COMPRA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
        jdbc.execute("ALTER TABLE APP_COMPRA ADD COLUMN IF NOT EXISTS PRODUCTO VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_COMPRA ADD COLUMN IF NOT EXISTS CANTIDAD NUMBER");
        jdbc.execute("ALTER TABLE APP_COMPRA ADD COLUMN IF NOT EXISTS PROVEEDOR VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_COMPRA ADD COLUMN IF NOT EXISTS FECHA DATE");
        jdbc.execute("ALTER TABLE APP_COMPRA ADD COLUMN IF NOT EXISTS ESTADO VARCHAR2(500)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS APP_CONFIGURACION (ID_CONFIGURACION NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
        jdbc.execute("ALTER TABLE APP_CONFIGURACION ADD COLUMN IF NOT EXISTS OPCION VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_CONFIGURACION ADD COLUMN IF NOT EXISTS VALOR VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_CONFIGURACION ADD COLUMN IF NOT EXISTS DESCRIPCION VARCHAR2(500)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS APP_CONTROL_SANITARIO (ID_CONTROL NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
        jdbc.execute("ALTER TABLE APP_CONTROL_SANITARIO ADD COLUMN IF NOT EXISTS PUNTO_CONTROL VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_CONTROL_SANITARIO ADD COLUMN IF NOT EXISTS TEMPERATURA_C NUMBER");
        jdbc.execute("ALTER TABLE APP_CONTROL_SANITARIO ADD COLUMN IF NOT EXISTS FECHA_HORA TIMESTAMP");
        jdbc.execute("ALTER TABLE APP_CONTROL_SANITARIO ADD COLUMN IF NOT EXISTS RESPONSABLE_ID NUMBER");
        jdbc.execute("ALTER TABLE APP_CONTROL_SANITARIO ADD COLUMN IF NOT EXISTS ESTADO VARCHAR2(500)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS APP_INCIDENCIA (ID_INCIDENCIA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
        jdbc.execute("ALTER TABLE APP_INCIDENCIA ADD COLUMN IF NOT EXISTS TIPO VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_INCIDENCIA ADD COLUMN IF NOT EXISTS AREA VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_INCIDENCIA ADD COLUMN IF NOT EXISTS DESCRIPCION VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_INCIDENCIA ADD COLUMN IF NOT EXISTS RESPONSABLE_ID NUMBER");
        jdbc.execute("ALTER TABLE APP_INCIDENCIA ADD COLUMN IF NOT EXISTS ESTADO VARCHAR2(500)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS APP_INSUMO (ID_INSUMO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
        jdbc.execute("ALTER TABLE APP_INSUMO ADD COLUMN IF NOT EXISTS NOMBRE VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_INSUMO ADD COLUMN IF NOT EXISTS CATEGORIA VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_INSUMO ADD COLUMN IF NOT EXISTS STOCK_ACTUAL NUMBER");
        jdbc.execute("ALTER TABLE APP_INSUMO ADD COLUMN IF NOT EXISTS UNIDAD VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_INSUMO ADD COLUMN IF NOT EXISTS STOCK_MINIMO NUMBER");
        jdbc.execute("CREATE TABLE IF NOT EXISTS APP_LIMPIEZA (ID_LIMPIEZA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
        jdbc.execute("ALTER TABLE APP_LIMPIEZA ADD COLUMN IF NOT EXISTS AREA VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_LIMPIEZA ADD COLUMN IF NOT EXISTS TAREA VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_LIMPIEZA ADD COLUMN IF NOT EXISTS RESPONSABLE_ID NUMBER");
        jdbc.execute("ALTER TABLE APP_LIMPIEZA ADD COLUMN IF NOT EXISTS FRECUENCIA VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_LIMPIEZA ADD COLUMN IF NOT EXISTS ESTADO VARCHAR2(500)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS APP_MERMA (ID_MERMA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
        jdbc.execute("ALTER TABLE APP_MERMA ADD COLUMN IF NOT EXISTS PRODUCTO VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_MERMA ADD COLUMN IF NOT EXISTS CANTIDAD NUMBER");
        jdbc.execute("ALTER TABLE APP_MERMA ADD COLUMN IF NOT EXISTS UNIDAD VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_MERMA ADD COLUMN IF NOT EXISTS MOTIVO VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_MERMA ADD COLUMN IF NOT EXISTS FECHA DATE");
        jdbc.execute("CREATE TABLE IF NOT EXISTS APP_MISE_EN_PLACE (ID_MISE NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
        jdbc.execute("ALTER TABLE APP_MISE_EN_PLACE ADD COLUMN IF NOT EXISTS PREPARACION VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_MISE_EN_PLACE ADD COLUMN IF NOT EXISTS CANTIDAD NUMBER");
        jdbc.execute("ALTER TABLE APP_MISE_EN_PLACE ADD COLUMN IF NOT EXISTS RESPONSABLE_ID NUMBER");
        jdbc.execute("ALTER TABLE APP_MISE_EN_PLACE ADD COLUMN IF NOT EXISTS HORA_LIMITE VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_MISE_EN_PLACE ADD COLUMN IF NOT EXISTS ESTADO VARCHAR2(500)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS APP_PRODUCCION (ID_PRODUCCION NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
        jdbc.execute("ALTER TABLE APP_PRODUCCION ADD COLUMN IF NOT EXISTS PREPARACION VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_PRODUCCION ADD COLUMN IF NOT EXISTS CANTIDAD NUMBER");
        jdbc.execute("ALTER TABLE APP_PRODUCCION ADD COLUMN IF NOT EXISTS UNIDAD VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_PRODUCCION ADD COLUMN IF NOT EXISTS RESPONSABLE_ID NUMBER");
        jdbc.execute("ALTER TABLE APP_PRODUCCION ADD COLUMN IF NOT EXISTS FECHA DATE");
        jdbc.execute("CREATE TABLE IF NOT EXISTS APP_REPORTE (ID_REPORTE NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
        jdbc.execute("ALTER TABLE APP_REPORTE ADD COLUMN IF NOT EXISTS NOMBRE VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_REPORTE ADD COLUMN IF NOT EXISTS PERIODO VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_REPORTE ADD COLUMN IF NOT EXISTS FECHA DATE");
        jdbc.execute("ALTER TABLE APP_REPORTE ADD COLUMN IF NOT EXISTS ESTADO VARCHAR2(500)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS APP_RESERVA (ID_RESERVA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
        jdbc.execute("ALTER TABLE APP_RESERVA ADD COLUMN IF NOT EXISTS CLIENTE VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_RESERVA ADD COLUMN IF NOT EXISTS FECHA DATE");
        jdbc.execute("ALTER TABLE APP_RESERVA ADD COLUMN IF NOT EXISTS HORA VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_RESERVA ADD COLUMN IF NOT EXISTS PERSONAS NUMBER");
        jdbc.execute("ALTER TABLE APP_RESERVA ADD COLUMN IF NOT EXISTS CONTACTO VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_RESERVA ADD COLUMN IF NOT EXISTS ESTADO VARCHAR2(500)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS APP_TAREA_DIARIA (ID_TAREA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
        jdbc.execute("ALTER TABLE APP_TAREA_DIARIA ADD COLUMN IF NOT EXISTS TAREA VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_TAREA_DIARIA ADD COLUMN IF NOT EXISTS RESPONSABLE_ID NUMBER");
        jdbc.execute("ALTER TABLE APP_TAREA_DIARIA ADD COLUMN IF NOT EXISTS FECHA DATE");
        jdbc.execute("ALTER TABLE APP_TAREA_DIARIA ADD COLUMN IF NOT EXISTS ESTADO VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_TAREA_DIARIA ADD COLUMN IF NOT EXISTS AREA VARCHAR2(500)");
        jdbc.execute("CREATE TABLE IF NOT EXISTS APP_TURNO (ID_TURNO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
        jdbc.execute("ALTER TABLE APP_TURNO ADD COLUMN IF NOT EXISTS EMPLEADO_ID NUMBER");
        jdbc.execute("ALTER TABLE APP_TURNO ADD COLUMN IF NOT EXISTS FECHA DATE");
        jdbc.execute("ALTER TABLE APP_TURNO ADD COLUMN IF NOT EXISTS HORA_INICIO VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_TURNO ADD COLUMN IF NOT EXISTS HORA_TERMINO VARCHAR2(500)");
        jdbc.execute("ALTER TABLE APP_TURNO ADD COLUMN IF NOT EXISTS AREA VARCHAR2(500)");
        try(var connection=jdbc.getDataSource().getConnection()) {
            org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript(connection,new org.springframework.core.io.ClassPathResource("marigex-test-schema.sql"));
        }
        String[] roles={"EMPRESA","TRABAJADOR","EMPLEADO","JEFE_COCINA","JEFE_SALON"};
        for(int i=1;i<=5;i++) {
            jdbc.update("INSERT INTO APP_EMPLEADO VALUES(?,?,?,?,?)",i,"Persona "+i,"Cocinero",i==3?"Salón":"Cocina","ACTIVO");
            jdbc.update("INSERT INTO APP_USUARIO(ID_USUARIO,ID_EMPLEADO,USUARIO,ROL,ACTIVO) VALUES(?,?,?,?,?)",i,i,"user"+i,roles[i-1],"S");
        }
        jdbc.update("INSERT INTO APP_TAREA_DIARIA(ID_TAREA,TAREA,RESPONSABLE_ID,FECHA,ESTADO,AREA) VALUES(10,'Preparar',2,DATE '2026-09-28','PENDIENTE','COCINA')");
        jdbc.update("INSERT INTO APP_TAREA_DIARIA(ID_TAREA,TAREA,RESPONSABLE_ID,FECHA,ESTADO,AREA) VALUES(11,'Mesas',3,DATE '2026-09-28','PENDIENTE','SALON')");
        jdbc.update("INSERT INTO APP_ASISTENCIA VALUES(10,3,DATE '2026-09-28','09:00','18:00','PRESENTE')");
        owner=session(1); worker=session(2); otherWorker=session(3); kitchen=session(4); salon=session(5);
    }
    @Test void unauthenticatedCannotReadProtectedEndpoints() throws Exception {
        for(String path:new String[]{"/api/plazas","/api/horarios","/api/areas/COCINA/empleados","/api/modulos/tareas-diarias?area=COCINA"})
            mvc.perform(get(path)).andExpect(status().isUnauthorized());
    }
    @Test void workersCannotUseAdministrativeEndpointsEvenWithDirectRequests() throws Exception {
        for(var s:new MockHttpSession[]{worker,otherWorker}) {
            mvc.perform(post("/api/plazas").session(s).contentType("application/json").content("{\"position\":\"Cocinero\",\"area\":\"COCINA\",\"slots\":3,\"active\":true}")).andExpect(status().isForbidden());
            mvc.perform(delete("/api/horarios/1").session(s)).andExpect(status().isForbidden());
            mvc.perform(post("/api/empleados").session(s).contentType("application/json").content("{\"name\":\"Intruso\",\"role\":\"Cargo\",\"area\":\"Cocina\"}")).andExpect(status().isForbidden());
            mvc.perform(post("/api/modulos/turnos").session(s).contentType("application/json").content("{\"values\":[],\"references\":[]}")).andExpect(status().isForbidden());
        }
        mvc.perform(get("/api/modulos/turnos").session(worker)).andExpect(status().isOk());
        assertEquals(5,jdbc.queryForObject("SELECT COUNT(*) FROM APP_EMPLEADO",Integer.class));
    }
    @Test void areasAndAssignmentsAreEnforced() throws Exception {
        mvc.perform(get("/api/modulos/tareas-diarias?area=COCINA").session(worker)).andExpect(status().isOk()).andExpect(jsonPath("$.length()").value(1)).andExpect(jsonPath("$[0].id").value(10));
        mvc.perform(get("/api/modulos/tareas-diarias?area=SALON").session(worker)).andExpect(status().isOk());
        mvc.perform(get("/api/modulos/tareas-diarias").session(owner)).andExpect(status().isBadRequest());
        mvc.perform(get("/api/areas/Salón/empleados").session(otherWorker)).andExpect(status().isOk()).andExpect(jsonPath("$.length()").value(1));
        mvc.perform(get("/api/areas/BARRA/empleados").session(worker)).andExpect(status().isOk());
        mvc.perform(get("/api/modulos/tareas-diarias?area=SALON").session(kitchen)).andExpect(status().isOk()).andExpect(jsonPath("$[0].id").value(11));
        String mismatched="{\"values\":[\"Tarea\",\"3\",\"2026-09-28\",\"PENDIENTE\",\"COCINA\"],\"references\":[null,3,null,null,null]}";
        mvc.perform(put("/api/modulos/tareas-diarias/10").session(owner).contentType("application/json").content(mismatched)).andExpect(status().isBadRequest());
        assertEquals(2,jdbc.queryForObject("SELECT RESPONSABLE_ID FROM APP_TAREA_DIARIA WHERE ID_TAREA=10",Integer.class));
    }
    @Test void cannotOverwriteAnotherWorkersAttendance() throws Exception {
        mvc.perform(put("/api/modulos/asistencia/10").session(worker).contentType("application/json").content("{\"values\":[\"2\",\"2026-09-28\",\"08:00\",\"19:00\",\"PRESENTE\"],\"references\":[2,null,null,null,null]}")).andExpect(status().isForbidden());
        assertEquals(3,jdbc.queryForObject("SELECT EMPLEADO_ID FROM APP_ASISTENCIA WHERE ID_ASISTENCIA=10",Integer.class));
    }
    @Test void evidenceRequiresAssignmentAndCanBeApprovedWithoutDeletingImage() throws Exception {
        jdbc.update("UPDATE APP_TAREA_DIARIA SET RESPONSABLE_ID=1 WHERE ID_TAREA=10");
        var file=new MockMultipartFile("photo","foto.png","image/png",PNG);
        mvc.perform(multipart("/api/evidencias").file(file).param("taskId","11").session(worker)).andExpect(status().isForbidden());
        mvc.perform(multipart("/api/evidencias").file(file).param("taskId","10").session(owner)).andExpect(status().isCreated());
        mvc.perform(multipart("/api/evidencias").file(file).param("taskId","10").session(owner)).andExpect(status().isForbidden());
        long id=jdbc.queryForObject("SELECT ID_EVIDENCIA FROM APP_EVIDENCIA_TAREA",Long.class);
        mvc.perform(post("/api/evidencias/"+id+"/revisar").session(worker)).andExpect(status().isForbidden());
        mvc.perform(post("/api/evidencias/"+id+"/revisar").session(owner)).andExpect(status().isOk());
        assertEquals("COMPLETADA",jdbc.queryForObject("SELECT ESTADO FROM APP_TAREA_DIARIA WHERE ID_TAREA=10",String.class));
        mvc.perform(get("/api/evidencias/"+id+"/foto").session(owner)).andExpect(status().isOk()).andExpect(content().bytes(PNG));
        assertEquals(2,jdbc.queryForObject("SELECT COUNT(*) FROM APP_ACTIVIDAD WHERE ACCION IN ('ENVIAR_TAREA','COMPLETAR_TAREA')",Integer.class));
    }
    @Test void schedulePersistsInDatabaseAndWorkerCanOnlyRead() throws Exception {
        var file=new MockMultipartFile("image","semana.png","image/png",PNG);
        mvc.perform(multipart("/api/horarios").file(file).param("title","Semana").session(worker)).andExpect(status().isForbidden());
        mvc.perform(multipart("/api/horarios").file(file).param("title","Semana").session(owner)).andExpect(status().isCreated());
        long id=jdbc.queryForObject("SELECT ID_HORARIO FROM APP_HORARIO_IMAGEN",Long.class);
        assertArrayEquals(PNG,jdbc.queryForObject("SELECT IMAGEN FROM APP_HORARIO_IMAGEN WHERE ID_HORARIO=?",byte[].class,id));
        mvc.perform(get("/api/horarios/"+id+"/imagen").session(worker)).andExpect(status().isOk()).andExpect(header().string("Cache-Control","no-store")).andExpect(content().bytes(PNG));
        mvc.perform(multipart("/api/horarios").file(file).param("title","Reemplazo").param("replaceId",String.valueOf(id)).session(owner)).andExpect(status().isCreated());
        assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM APP_HORARIO_IMAGEN",Integer.class));
        assertEquals("Reemplazo",jdbc.queryForObject("SELECT TITULO FROM APP_HORARIO_IMAGEN",String.class));
        mvc.perform(delete("/api/horarios/"+id).session(owner)).andExpect(status().isNoContent());
        mvc.perform(get("/api/horarios/"+id+"/imagen").session(worker)).andExpect(status().isNotFound());
    }
    @Test void malformedAndOversizeImagesDoNotWriteData() throws Exception {
        for(byte[] bytes:new byte[][]{"<script>alert(1)</script>".getBytes(),new byte[4*1024*1024+1]})
            mvc.perform(multipart("/api/horarios").file(new MockMultipartFile("image","f.png","image/png",bytes)).param("title","Mala").session(owner)).andExpect(status().isBadRequest());
        assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM APP_HORARIO_IMAGEN",Integer.class));
    }
    @Test void plazasReuseActiveEmployeeCargoAndArea() throws Exception {
        mvc.perform(post("/api/plazas").session(owner).contentType("application/json").content("{\"position\":\"Cocinero\",\"area\":\"Salón\",\"slots\":3,\"active\":true}")).andExpect(status().isCreated());
        mvc.perform(get("/api/plazas").session(owner)).andExpect(status().isOk()).andExpect(jsonPath("$[0].occupied").value(1)).andExpect(jsonPath("$[0].area").value("SALON"));
    }
    @Test void workerCannotCreateIncidentButCanConsultActivity() throws Exception {
        mvc.perform(post("/api/modulos/incidencias").session(worker).contentType("application/json").content("{\"values\":[]}" )).andExpect(status().isForbidden());
        assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM APP_INCIDENCIA",Integer.class));
        mvc.perform(get("/api/dashboard/overview").session(worker)).andExpect(status().isOk());
    }
    @Test void inventoryCrudStillWorksForManager() throws Exception {
        mvc.perform(post("/api/modulos/inventario").session(owner).contentType("application/json").content("{\"values\":[\"Arroz\",\"Secos\",\"10\",\"kg\",\"2\"]}")).andExpect(status().isCreated());
        mvc.perform(get("/api/modulos/inventario").session(owner)).andExpect(status().isOk()).andExpect(jsonPath("$[0].values[0]").value("Arroz"));
        mvc.perform(post("/api/modulos/inventario").session(worker).contentType("application/json").content("{\"values\":[]}")).andExpect(status().isForbidden());
    }
    @Test void inactiveAccountLosesExistingSessionAccess() throws Exception {
        jdbc.update("UPDATE APP_USUARIO SET ACTIVO='N' WHERE ID_USUARIO=2");
        mvc.perform(get("/api/horarios").session(worker)).andExpect(status().isUnauthorized());
    }

    @Test void administrativeRolesHaveFullAccessAndIndependentHashedAccounts() throws Exception {
        var mappings=context.getBean(org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.class);
        long createMappings=mappings.getHandlerMethods().keySet().stream().filter(info ->
            info.getPatternValues().contains("/api/auth/users") && info.getMethodsCondition().getMethods().contains(org.springframework.web.bind.annotation.RequestMethod.POST)).count();
        assertEquals(1,createMappings,"Debe existir un único endpoint para crear accesos");
        String[] roles={"ADMIN","EMPRESA","JEFE_SALON","JEFE_COCINA","JEFE_LOCAL","TRABAJADOR","EMPLEADO"};
        for(int i=0;i<roles.length;i++) {
            int employeeId=20+i;
            jdbc.update("INSERT INTO APP_EMPLEADO VALUES(?,?,?,?,?)",employeeId,"Cuenta "+i,"Mesero","Salón","ACTIVO");
            String username="cuenta"+i;
            String password="ClavePersonalSegura"+i;
            String body="{\"employeeId\":"+employeeId+",\"username\":\""+username+"\",\"password\":\""+password+"\",\"role\":\""+roles[i]+"\"}";
            mvc.perform(post("/api/auth/users").session(owner).contentType("application/json").content(body)).andExpect(status().isCreated());
            String stored=jdbc.queryForObject("SELECT CLAVE_HASH FROM APP_USUARIO WHERE USUARIO=?",String.class,username);
            assertTrue(stored.startsWith("pbkdf2$180000$")); assertNotEquals(password,stored);
            var signedIn=new MockHttpSession();
            mvc.perform(post("/api/auth/login").session(signedIn).contentType("application/json")
                .content("{\"username\":\""+username+"\",\"password\":\""+password+"\"}"))
                .andExpect(status().isOk()).andExpect(jsonPath("$.role").value(roles[i]));
            mvc.perform(post("/api/auth/login").contentType("application/json")
                .content("{\"username\":\""+username+"\",\"password\":\"otraClaveIncorrecta\"}"))
                .andExpect(status().isUnauthorized());
            boolean admin=i<5;
            mvc.perform(get("/api/plazas").session(signedIn)).andExpect(status().isOk());
            mvc.perform(get("/api/empleados").session(signedIn)).andExpect(status().isOk());
            mvc.perform(get("/api/modulos/tareas-diarias?area=COCINA").session(signedIn)).andExpect(status().isOk());
            mvc.perform(get("/api/dashboard/overview").session(signedIn)).andExpect(status().isOk());
            mvc.perform(post("/api/auth/users").session(signedIn).contentType("application/json").content("{}"))
                .andExpect(admin?status().isBadRequest():status().isForbidden());
            var file=new MockMultipartFile("image","semana.png","image/png",PNG);
            mvc.perform(multipart("/api/horarios").file(file).param("title","Semana").session(signedIn))
                .andExpect(admin?status().isCreated():status().isForbidden());
            if(admin) {
                long id=jdbc.queryForObject("SELECT MAX(ID_HORARIO) FROM APP_HORARIO_IMAGEN",Long.class);
                mvc.perform(delete("/api/horarios/"+id).session(signedIn)).andExpect(status().isNoContent());
            }
        }
        assertEquals("EMPRESA",jdbc.queryForObject("SELECT ROL FROM APP_USUARIO WHERE ID_USUARIO=1",String.class));
    }
    @Test void accountCreationRejectsInvalidAndDuplicateInputs() throws Exception {
        jdbc.update("INSERT INTO APP_EMPLEADO VALUES(20,'Nueva persona','Mesero','Salón','ACTIVO')");
        String valid="{\"employeeId\":20,\"username\":\"nuevo\",\"password\":\"ClaveSegura123\",\"role\":\"JEFE_LOCAL\"}";
        mvc.perform(post("/api/auth/users").contentType("application/json").content(valid)).andExpect(status().isUnauthorized());
        mvc.perform(post("/api/auth/users").session(worker).contentType("application/json").content(valid)).andExpect(status().isForbidden());
        for(String invalid:new String[]{valid.replace("JEFE_LOCAL","SUPERUSER"),valid.replace("ClaveSegura123","corta"),valid.replace("nuevo","ab")})
            mvc.perform(post("/api/auth/users").session(owner).contentType("application/json").content(invalid)).andExpect(status().isBadRequest());
        mvc.perform(post("/api/auth/users").session(owner).contentType("application/json").content(valid)).andExpect(status().isCreated());
        mvc.perform(post("/api/auth/users").session(owner).contentType("application/json").content(valid)).andExpect(status().isBadRequest());
        assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM APP_USUARIO WHERE ID_EMPLEADO=20",Integer.class));
    }

    private MockHttpSession passwordAccount(String role) throws Exception {
        jdbc.update("INSERT INTO APP_EMPLEADO VALUES(50,'Cuenta clave','Mesero','Salón','ACTIVO')");
        mvc.perform(post("/api/auth/users").session(owner).contentType("application/json")
            .content("{\"employeeId\":50,\"username\":\"claveusuario\",\"password\":\"AnteriorSegura123\",\"role\":\""+role+"\"}"))
            .andExpect(status().isCreated());
        return session(jdbc.queryForObject("SELECT ID_USUARIO FROM APP_USUARIO WHERE ID_EMPLEADO=50",Long.class));
    }
    private String passwordBody(String current, String next, String confirmation) {
        return "{\"currentPassword\":\""+current+"\",\"newPassword\":\""+next+"\",\"confirmPassword\":\""+confirmation+"\"}";
    }
    @Test void ownPasswordChangesHashAndReplacesLoginCredential() throws Exception {
        for(String role:new String[]{"EMPRESA","ADMIN","JEFE_SALON","JEFE_COCINA","JEFE_LOCAL","TRABAJADOR","EMPLEADO"}) {
            var account=passwordAccount(role);
            String old=jdbc.queryForObject("SELECT CLAVE_HASH FROM APP_USUARIO WHERE ID_EMPLEADO=50",String.class);
            String body=passwordBody("AnteriorSegura123","NuevaSegura456","NuevaSegura456");
            // Un ID inyectado no puede seleccionar otra cuenta: el DTO solo contiene contraseñas.
            body=body.substring(0,body.length()-1)+",\"userId\":1,\"employeeId\":1}";
            mvc.perform(post("/api/auth/password").session(account).contentType("application/json").content(body))
                .andExpect(status().isOk()).andExpect(jsonPath("$.message").value("Contraseña actualizada correctamente"));
            String changed=jdbc.queryForObject("SELECT CLAVE_HASH FROM APP_USUARIO WHERE ID_EMPLEADO=50",String.class);
            assertNotEquals(old,changed); assertNotEquals("NuevaSegura456",changed); assertTrue(changed.startsWith("pbkdf2$180000$"));
            assertNull(jdbc.queryForObject("SELECT CLAVE_HASH FROM APP_USUARIO WHERE ID_USUARIO=1",String.class));
            assertEquals(role,jdbc.queryForObject("SELECT ROL FROM APP_USUARIO WHERE ID_EMPLEADO=50",String.class));
            mvc.perform(post("/api/auth/login").contentType("application/json").content("{\"username\":\"claveusuario\",\"password\":\"AnteriorSegura123\"}")).andExpect(status().isUnauthorized());
            mvc.perform(post("/api/auth/login").contentType("application/json").content("{\"username\":\"claveusuario\",\"password\":\"NuevaSegura456\"}")).andExpect(status().isOk());
            mvc.perform(get("/api/horarios").session(account)).andExpect(status().isOk());
            jdbc.update("DELETE FROM APP_USUARIO WHERE ID_EMPLEADO=50"); jdbc.update("DELETE FROM APP_EMPLEADO WHERE ID_EMPLEADO=50");
        }
    }
    @Test void invalidPasswordChangesLeaveHashUntouched() throws Exception {
        var account=passwordAccount("TRABAJADOR");
        String original=jdbc.queryForObject("SELECT CLAVE_HASH FROM APP_USUARIO WHERE ID_EMPLEADO=50",String.class);
        mvc.perform(post("/api/auth/password").session(account).contentType("application/json")
            .content(passwordBody("Incorrecta123","NuevaSegura456","NuevaSegura456")))
            .andExpect(status().isBadRequest()).andExpect(jsonPath("$.error").value("La contraseña actual es incorrecta."));
        for(String body:new String[]{"{}",passwordBody("AnteriorSegura123","corta","corta"),passwordBody("AnteriorSegura123","NuevaSegura456","NoCoincide123"),passwordBody("AnteriorSegura123","x".repeat(201),"x".repeat(201)),passwordBody("AnteriorSegura123","AnteriorSegura123","AnteriorSegura123")}) {
            mvc.perform(post("/api/auth/password").session(account).contentType("application/json").content(body)).andExpect(status().isBadRequest());
            assertEquals(original,jdbc.queryForObject("SELECT CLAVE_HASH FROM APP_USUARIO WHERE ID_EMPLEADO=50",String.class));
        }
        mvc.perform(post("/api/auth/password").contentType("application/json").content(passwordBody("AnteriorSegura123","NuevaSegura456","NuevaSegura456"))).andExpect(status().isUnauthorized());
        jdbc.update("UPDATE APP_USUARIO SET ACTIVO='N' WHERE ID_EMPLEADO=50");
        mvc.perform(post("/api/auth/password").session(account).contentType("application/json").content(passwordBody("AnteriorSegura123","NuevaSegura456","NuevaSegura456"))).andExpect(status().isUnauthorized());
        assertEquals(original,jdbc.queryForObject("SELECT CLAVE_HASH FROM APP_USUARIO WHERE ID_EMPLEADO=50",String.class));
    }

    @Test void workerCanReadEveryModuleButCannotMutateAnyModule() throws Exception {
        // H2 does not implement Oracle's ISO-week TRUNC. Stub only this aggregate,
        // leaving every permission check and other module query on the real test database.
        org.mockito.Mockito.doReturn(0L).when(jdbc).queryForObject("SELECT COUNT(*) FROM APP_MERMA WHERE FECHA >= TRUNC(SYSDATE, 'IW')",Long.class);
        for(String module:new String[]{"asistencia","cocina","compras","configuracion","control-sanitario","incidencias","inventario","limpieza","mermas","mise-en-place","produccion","reportes","reservas","tareas-diarias","turnos"}) {
            String url="/api/modulos/"+module;
            mvc.perform(get(url+(module.equals("tareas-diarias")?"?area=SALON":"")).session(worker)).andExpect(status().isOk());
            mvc.perform(post(url).session(worker).contentType("application/json").content("{\"values\":[]}")).andExpect(status().isForbidden());
            mvc.perform(put(url+"/10").session(worker).contentType("application/json").content("{\"values\":[]}")).andExpect(status().isForbidden());
            mvc.perform(delete(url+"/10").session(worker)).andExpect(status().isForbidden());
            mvc.perform(patch(url+"/10").session(worker).contentType("application/json").content("{}")).andExpect(status().isMethodNotAllowed());
        }
        for(String path:new String[]{"/api/dashboard","/api/dashboard/overview","/api/empleados","/api/plazas","/api/horarios","/api/evidencias?area=SALON","/api/modulos/tareas-diarias?area=SIN_AREA"})
            mvc.perform(get(path).session(worker)).andExpect(status().isOk());
        for(String area:new String[]{"COCINA","SALON","BARRA","COPERIA"})
            mvc.perform(get("/api/areas/"+area+"/empleados").session(worker)).andExpect(status().isOk());
        mvc.perform(get("/api/empleados").session(worker)).andExpect(jsonPath("$.length()").value(5));
        mvc.perform(get("/api/modulos/asistencia").session(worker)).andExpect(jsonPath("$[0].references[0]").value(3));
        jdbc.update("INSERT INTO APP_EVIDENCIA_TAREA(ID_TAREA,ID_EMPLEADO,NOMBRE_ARCHIVO,TIPO_CONTENIDO,FOTO) VALUES(11,3,'foto.png','image/png',?)",PNG);
        long id=jdbc.queryForObject("SELECT ID_EVIDENCIA FROM APP_EVIDENCIA_TAREA",Long.class);
        mvc.perform(get("/api/evidencias/"+id+"/foto").session(worker)).andExpect(status().isOk()).andExpect(content().bytes(PNG));
        mvc.perform(delete("/api/evidencias/"+id).session(worker)).andExpect(status().isForbidden());
        mvc.perform(post("/api/evidencias/"+id+"/revisar").session(worker)).andExpect(status().isForbidden());
        mvc.perform(multipart("/api/evidencias").file(new MockMultipartFile("photo","f.png","image/png",PNG)).param("taskId","11").session(worker)).andExpect(status().isForbidden());
        mvc.perform(put("/api/empleados/2").session(worker).contentType("application/json").content("{}")).andExpect(status().isForbidden());
        mvc.perform(delete("/api/empleados/2").session(worker)).andExpect(status().isForbidden());
        mvc.perform(put("/api/plazas/1").session(worker).contentType("application/json").content("{\"position\":\"Cocinero\",\"area\":\"COCINA\",\"slots\":1,\"active\":true}")).andExpect(status().isForbidden());
    }

    @Test void personalNotificationsCannotBeReadOrChangedByAnotherUser() throws Exception {
        notifications.employee(2,"Tareas diarias","Tu tarea"); notifications.employee(3,"Horarios","Otro horario"); notifications.administrators("Incidencias","Solo administración");
        mvc.perform(get("/api/notificaciones").session(worker)).andExpect(status().isOk()).andExpect(jsonPath("$.unread").value(1)).andExpect(jsonPath("$.items.length()").value(1)).andExpect(jsonPath("$.items[0].message").value("Tu tarea"));
        long own=jdbc.queryForObject("SELECT ID_NOTIFICACION FROM APP_NOTIFICACION WHERE ID_USUARIO=2",Long.class);
        long other=jdbc.queryForObject("SELECT ID_NOTIFICACION FROM APP_NOTIFICACION WHERE ID_USUARIO=3",Long.class);
        mvc.perform(post("/api/notificaciones/"+other+"/leida").session(worker)).andExpect(status().isNotFound());
        mvc.perform(post("/api/notificaciones/"+own+"/leida").session(worker)).andExpect(status().isOk());
        mvc.perform(get("/api/notificaciones").session(worker)).andExpect(jsonPath("$.unread").value(0));
        mvc.perform(post("/api/notificaciones/leidas").session(worker)).andExpect(status().isOk());
        assertEquals("N",jdbc.queryForObject("SELECT LEIDA FROM APP_NOTIFICACION WHERE ID_NOTIFICACION=?",String.class,other));
        mvc.perform(get("/api/notificaciones")).andExpect(status().isUnauthorized());
        mvc.perform(get("/api/notificaciones").session(owner)).andExpect(jsonPath("$.items[0].message").value("Solo administración"));
    }
    @Test void assignmentsAndImageSchedulesNotifyOnlyAffectedEmployees() throws Exception {
        mvc.perform(post("/api/modulos/tareas-diarias").session(owner).contentType("application/json").content("{\"values\":[\"Preparar\",\"\",\"2026-10-01\",\"PENDIENTE\",\"COCINA\"],\"references\":[null,2,null,null,null]}")).andExpect(status().isCreated());
        mvc.perform(multipart("/api/horarios").file(new MockMultipartFile("image","h.png","image/png",PNG)).param("title","Semana").param("employeeIds","2").session(owner)).andExpect(status().isCreated());
        mvc.perform(get("/api/notificaciones").session(worker)).andExpect(jsonPath("$.unread").value(2));
        mvc.perform(get("/api/notificaciones").session(otherWorker)).andExpect(jsonPath("$.unread").value(0));
        mvc.perform(multipart("/api/horarios").file(new MockMultipartFile("image","h.png","image/png",PNG)).param("title","Semana").param("employeeIds","999").session(owner)).andExpect(status().isBadRequest());
        assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM APP_HORARIO_IMAGEN",Integer.class));
        long schedule=jdbc.queryForObject("SELECT ID_HORARIO FROM APP_HORARIO_IMAGEN",Long.class);
        mvc.perform(get("/api/horarios").session(worker)).andExpect(jsonPath("$[0].employeeIds[0]").value(2));
        mvc.perform(multipart("/api/horarios").file(new MockMultipartFile("image","h.png","image/png",PNG)).param("title","Reemplazado").param("replaceId",String.valueOf(schedule)).session(owner)).andExpect(status().isCreated());
        mvc.perform(get("/api/notificaciones").session(worker)).andExpect(jsonPath("$.unread").value(3));
        mvc.perform(delete("/api/horarios/"+schedule).session(owner)).andExpect(status().isNoContent());
        mvc.perform(get("/api/notificaciones").session(worker)).andExpect(jsonPath("$.unread").value(4));
        mvc.perform(get("/api/notificaciones").session(otherWorker)).andExpect(jsonPath("$.unread").value(0));

    }
    private String proposal(long employee,String from,String to) { return "{\"shifts\":[{\"employeeId\":"+employee+",\"date\":\"2026-10-05\",\"start\":\""+from+"\",\"end\":\""+to+"\"}],\"warnings\":[]}"; }
    private String generateDraft() throws Exception {
        org.mockito.Mockito.when(ai.generate(org.mockito.ArgumentMatchers.anyString())).thenReturn(proposal(2,"09:00","17:00"));
        var response=mvc.perform(post("/api/horarios/ia/propuestas").session(owner).contentType("application/json").content("{\"instructions\":\"Generar semana\",\"startDate\":\"2026-10-05\"}")).andExpect(status().isOk()).andReturn();
        return new tools.jackson.databind.ObjectMapper().readTree(response.getResponse().getContentAsString()).path("id").asText();
    }
    @Test void aiProposalIsEditableExplicitAndPublishedOnlyOnce() throws Exception {
        String id=generateDraft();
        assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM APP_TURNO",Integer.class));
        assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM APP_NOTIFICACION",Integer.class));
        mvc.perform(get("/api/horarios/ia/propuestas").session(owner)).andExpect(jsonPath("$.length()").value(1));
        String url="/api/horarios/ia/propuestas/"+id+"/publicar";
        mvc.perform(post(url).session(worker).contentType("application/json").content(proposal(2,"10:00","18:00"))).andExpect(status().isForbidden());
        mvc.perform(post(url).session(kitchen).contentType("application/json").content(proposal(2,"10:00","18:00"))).andExpect(status().isNotFound());
        mvc.perform(post(url).session(owner).contentType("application/json").content(proposal(2,"10:00","18:00"))).andExpect(status().isOk());
        mvc.perform(post(url).session(owner).contentType("application/json").content(proposal(2,"10:00","18:00"))).andExpect(status().isOk());
        assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM APP_TURNO",Integer.class));
        assertEquals("10:00",jdbc.queryForObject("SELECT HORA_INICIO FROM APP_TURNO",String.class));
        mvc.perform(get("/api/notificaciones").session(worker)).andExpect(jsonPath("$.unread").value(1));
        mvc.perform(get("/api/notificaciones").session(otherWorker)).andExpect(jsonPath("$.unread").value(0));
        mvc.perform(get("/api/horarios/ia/propuestas").session(worker)).andExpect(status().isForbidden());
    }
    @Test void invalidAiAndEditedProposalsCannotWriteSchedules() throws Exception {
        String id=generateDraft(),url="/api/horarios/ia/propuestas/"+id+"/publicar";
        for(String body:new String[]{proposal(999,"09:00","17:00"),proposal(2,"18:00","09:00"),proposal(2,"01:00","23:00"),proposal(2,"25:00","26:00"),proposal(2,"09:00","17:00").replace("2026-10-05","2026-11-05"),"{\"shifts\":[],\"warnings\":[]}"})
            mvc.perform(post(url).session(owner).contentType("application/json").content(body)).andExpect(status().isBadRequest());
        jdbc.update("INSERT INTO APP_TURNO(EMPLEADO_ID,FECHA,HORA_INICIO,HORA_TERMINO,AREA) VALUES(2,DATE '2026-10-05','08:00','12:00','COCINA')");
        mvc.perform(post(url).session(owner).contentType("application/json").content(proposal(2,"09:00","17:00"))).andExpect(status().isBadRequest());
        assertEquals("BORRADOR",jdbc.queryForObject("SELECT ESTADO FROM APP_PROPUESTA_HORARIO WHERE ID_PROPUESTA=?",String.class,id));
        assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM APP_TURNO",Integer.class));
        org.mockito.Mockito.when(ai.generate(org.mockito.ArgumentMatchers.anyString())).thenReturn(proposal(999,"09:00","17:00"));
        mvc.perform(post("/api/horarios/ia/propuestas").session(owner).contentType("application/json").content("{\"instructions\":\"Semana\",\"startDate\":\"2026-10-05\"}")).andExpect(status().isBadRequest());
        assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM APP_PROPUESTA_HORARIO",Integer.class));
        mvc.perform(post("/api/horarios/ia/propuestas").session(worker).contentType("application/json").content("{}")).andExpect(status().isForbidden());
    }
    @Test void missingAiConfigurationHasClearError() {
        var client=new AiScheduleClient("","");assertFalse(client.configured());
        var ex=assertThrows(org.springframework.web.server.ResponseStatusException.class,()->client.generate("{}"));
        assertEquals(503,ex.getStatusCode().value());
    }

    @Test void workerTaskPhotoReviewAndRejectionFlow() throws Exception {
        // Login uses real PBKDF2 accounts created by the existing administrator endpoint.
        var account=passwordAccount("TRABAJADOR");
        var logged=mvc.perform(post("/api/auth/login").contentType("application/json").content("{\"username\":\"claveusuario\",\"password\":\"AnteriorSegura123\"}"))
            .andExpect(status().isOk()).andReturn();
        var employeeSession=(MockHttpSession)logged.getRequest().getSession();
        mvc.perform(post("/api/modulos/tareas-diarias").session(owner).contentType("application/json").content("{\"values\":[\"Revisar mesas\",\"\",\"2026-10-01\",\"PENDIENTE\",\"SALON\"],\"references\":[null,50,null,null,null]}"))
            .andExpect(status().isCreated());
        long task=jdbc.queryForObject("SELECT ID_TAREA FROM APP_TAREA_DIARIA WHERE RESPONSABLE_ID=50",Long.class);
        mvc.perform(get("/api/notificaciones").session(employeeSession)).andExpect(jsonPath("$.unread").value(1));
        mvc.perform(get("/api/modulos/tareas-diarias?area=SALON").session(employeeSession)).andExpect(status().isOk());
        var file=new MockMultipartFile("photo","foto.png","image/png",PNG);
        mvc.perform(multipart("/api/evidencias").file(file).param("taskId",String.valueOf(task)).session(otherWorker)).andExpect(status().isForbidden());
        mvc.perform(multipart("/api/evidencias").file(new MockMultipartFile("photo","fake.png","image/png","not an image".getBytes())).param("taskId",String.valueOf(task)).session(employeeSession)).andExpect(status().isBadRequest());
        mvc.perform(multipart("/api/evidencias").file(file).param("taskId",String.valueOf(task)).session(employeeSession)).andExpect(status().isCreated());
        assertEquals("EN_REVISION",jdbc.queryForObject("SELECT ESTADO FROM APP_TAREA_DIARIA WHERE ID_TAREA=?",String.class,task));
        long evidence=jdbc.queryForObject("SELECT ID_EVIDENCIA FROM APP_EVIDENCIA_TAREA WHERE ID_TAREA=?",Long.class,task);
        mvc.perform(multipart("/api/evidencias").file(file).param("taskId",String.valueOf(task)).session(employeeSession)).andExpect(status().isForbidden());
        mvc.perform(post("/api/evidencias/"+evidence+"/revisar").session(employeeSession)).andExpect(status().isForbidden());
        mvc.perform(get("/api/notificaciones").session(owner)).andExpect(jsonPath("$.unread").value(1));
        mvc.perform(get("/api/evidencias/"+evidence+"/foto").session(owner)).andExpect(content().bytes(PNG));
        mvc.perform(post("/api/evidencias/"+evidence+"/revisar?approved=false").session(owner)).andExpect(status().isOk());
        assertEquals("PENDIENTE",jdbc.queryForObject("SELECT ESTADO FROM APP_TAREA_DIARIA WHERE ID_TAREA=?",String.class,task));
        assertEquals("RECHAZADA",jdbc.queryForObject("SELECT RESULTADO FROM APP_EVIDENCIA_TAREA WHERE ID_EVIDENCIA=?",String.class,evidence));
        mvc.perform(multipart("/api/evidencias").file(file).param("taskId",String.valueOf(task)).session(employeeSession)).andExpect(status().isCreated());
        long next=jdbc.queryForObject("SELECT MAX(ID_EVIDENCIA) FROM APP_EVIDENCIA_TAREA WHERE ID_TAREA=?",Long.class,task);
        mvc.perform(post("/api/evidencias/"+next+"/revisar").session(owner)).andExpect(status().isOk());
        assertEquals("COMPLETADA",jdbc.queryForObject("SELECT ESTADO FROM APP_TAREA_DIARIA WHERE ID_TAREA=?",String.class,task));
        assertEquals(2,jdbc.queryForObject("SELECT COUNT(*) FROM APP_EVIDENCIA_TAREA WHERE ID_TAREA=?",Integer.class,task));
        mvc.perform(post("/api/auth/logout").session(employeeSession)).andExpect(status().isOk());
    }
 @Test
void inventoryCreateAndEditDoNotCreateAutomaticNotifications() throws Exception {
    int before = jdbc.queryForObject(
            "SELECT COUNT(*) FROM APP_NOTIFICACION",
            Integer.class);

    mvc.perform(post("/api/modulos/inventario")
            .session(owner)
            .contentType("application/json")
            .content("""
                    {
                      "values": [
                        "Producto prueba",
                        "Prueba",
                        "1",
                        "unidad",
                        "5",
                        "10",
                        "COCINA"
                      ]
                    }
                    """))
            .andExpect(status().isCreated());

    assertEquals(
            before,
            jdbc.queryForObject(
                    "SELECT COUNT(*) FROM APP_NOTIFICACION",
                    Integer.class));

    Long id = jdbc.queryForObject(
            "SELECT MAX(ID_INSUMO) FROM APP_INSUMO",
            Long.class);

    mvc.perform(put("/api/modulos/inventario/" + id)
            .session(owner)
            .contentType("application/json")
            .content("""
                    {
                      "values": [
                        "Producto prueba",
                        "Prueba",
                        "2",
                        "unidad",
                        "5",
                        "10",
                        "COCINA"
                      ]
                    }
                    """))
            .andExpect(status().isOk());

    assertEquals(
            before,
            jdbc.queryForObject(
                    "SELECT COUNT(*) FROM APP_NOTIFICACION",
                    Integer.class));
}

@Test
void inventoryCreateAndEditLowStockDoesNotNotifyAutomatically() throws Exception {
    int before = jdbc.queryForObject(
            "SELECT COUNT(*) FROM APP_NOTIFICACION",
            Integer.class);

    mvc.perform(post("/api/modulos/inventario")
            .session(owner)
            .contentType("application/json")
            .content("""
                    {
                      "values": [
                        "Producto prueba sin aviso",
                        "Prueba",
                        "2",
                        "unidad",
                        "5",
                        "10",
                        "COCINA"
                      ]
                    }
                    """))
            .andExpect(status().isCreated());

    assertEquals(
            before,
            jdbc.queryForObject(
                    "SELECT COUNT(*) FROM APP_NOTIFICACION",
                    Integer.class));

    Long id = jdbc.queryForObject(
            "SELECT MAX(ID_INSUMO) FROM APP_INSUMO",
            Long.class);

    mvc.perform(put("/api/modulos/inventario/" + id)
            .session(owner)
            .contentType("application/json")
            .content("""
                    {
                      "values": [
                        "Producto prueba sin aviso",
                        "Prueba",
                        "1",
                        "unidad",
                        "5",
                        "10",
                        "COCINA"
                      ]
                    }
                    """))
            .andExpect(status().isOk());

    assertEquals(
            before,
            jdbc.queryForObject(
                    "SELECT COUNT(*) FROM APP_NOTIFICACION",
                    Integer.class));
}
@Test
void inventorySendSeparatesCocinaAndBarra() throws Exception {
    jdbc.update(
            "INSERT INTO APP_INSUMO " +
            "(NOMBRE,CATEGORIA,STOCK_ACTUAL,UNIDAD,STOCK_MINIMO,STOCK_MAXIMO,ALERTA_ESTADO,GRUPO) " +
            "VALUES (?,?,?,?,?,?,?,?)",
            "Producto Cocina",
            "Prueba",
            1,
            "unidad",
            5,
            10,
            "NORMAL",
            "COCINA");

    jdbc.update(
            "INSERT INTO APP_INSUMO " +
            "(NOMBRE,CATEGORIA,STOCK_ACTUAL,UNIDAD,STOCK_MINIMO,STOCK_MAXIMO,ALERTA_ESTADO,GRUPO) " +
            "VALUES (?,?,?,?,?,?,?,?)",
            "Producto Barra",
            "Prueba",
            1,
            "unidad",
            5,
            10,
            "NORMAL",
            "BARRA");

    mvc.perform(post("/api/inventario/enviar")
            .session(owner)
            .contentType("application/json")
            .content("""
                    {"group":"COCINA"}
                    """))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.sent").value(true))
            .andExpect(jsonPath("$.group").value("COCINA"))
            .andExpect(jsonPath("$.count").value(1));

    mvc.perform(post("/api/inventario/enviar")
            .session(owner)
            .contentType("application/json")
            .content("""
                    {"group":"BARRA"}
                    """))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.sent").value(true))
            .andExpect(jsonPath("$.group").value("BARRA"))
            .andExpect(jsonPath("$.count").value(1));
}
@Test
void inventorySendExcludesStockAtOrAboveMinimum() throws Exception {
    jdbc.update(
            "INSERT INTO APP_INSUMO " +
            "(NOMBRE,CATEGORIA,STOCK_ACTUAL,UNIDAD,STOCK_MINIMO,STOCK_MAXIMO,ALERTA_ESTADO,GRUPO) " +
            "VALUES (?,?,?,?,?,?,?,?)",
            "Producto igual al minimo",
            "Prueba",
            5,
            "unidad",
            5,
            10,
            "NORMAL",
            "COCINA");

    jdbc.update(
            "INSERT INTO APP_INSUMO " +
            "(NOMBRE,CATEGORIA,STOCK_ACTUAL,UNIDAD,STOCK_MINIMO,STOCK_MAXIMO,ALERTA_ESTADO,GRUPO) " +
            "VALUES (?,?,?,?,?,?,?,?)",
            "Producto sobre el minimo",
            "Prueba",
            6,
            "unidad",
            5,
            10,
            "NORMAL",
            "COCINA");

    mvc.perform(post("/api/inventario/enviar")
            .session(owner)
            .contentType("application/json")
            .content("""
                    {"group":"COCINA"}
                    """))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.sent").value(false))
            .andExpect(jsonPath("$.group").value("COCINA"))
            .andExpect(jsonPath("$.count").value(0));
}
@Test
void inventorySendWithNoLowStockDoesNotCreateNotifications() throws Exception {
    jdbc.update(
            "INSERT INTO APP_INSUMO " +
            "(NOMBRE,CATEGORIA,STOCK_ACTUAL,UNIDAD,STOCK_MINIMO,STOCK_MAXIMO,ALERTA_ESTADO,GRUPO) " +
            "VALUES (?,?,?,?,?,?,?,?)",
            "Producto con stock suficiente",
            "Prueba",
            5,
            "unidad",
            5,
            10,
            "NORMAL",
            "BARRA");

    int before = jdbc.queryForObject(
            "SELECT COUNT(*) FROM APP_NOTIFICACION",
            Integer.class);

    mvc.perform(post("/api/inventario/enviar")
            .session(owner)
            .contentType("application/json")
            .content("""
                    {"group":"BARRA"}
                    """))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.sent").value(false))
            .andExpect(jsonPath("$.group").value("BARRA"))
            .andExpect(jsonPath("$.count").value(0));

    assertEquals(
            before,
            jdbc.queryForObject(
                    "SELECT COUNT(*) FROM APP_NOTIFICACION",
                    Integer.class));
}
@Test
void inventorySendRejectsInvalidGroups() throws Exception {
    String[] invalidGroups = {
            "SIN_GRUPO",
            "",
            "OTRO"
    };

    for (String group : invalidGroups) {
        mvc.perform(post("/api/inventario/enviar")
                .session(owner)
                .contentType("application/json")
                .content("""
                        {"group":"%s"}
                        """.formatted(group)))
                .andExpect(status().isBadRequest());
    }
}
@Test
void inventorySendRejectsUnauthorizedUser() throws Exception {
    mvc.perform(post("/api/inventario/enviar")
            .session(worker)
            .contentType("application/json")
            .content("""
                    {"group":"COCINA"}
                    """))
            .andExpect(status().isForbidden());
}
@Test
void inventorySendNotifiesEveryActiveAdministrativeAccountWithSameDetail() throws Exception {
    jdbc.update(
        "INSERT INTO APP_INSUMO " +
        "(NOMBRE,CATEGORIA,STOCK_ACTUAL,UNIDAD,STOCK_MINIMO,STOCK_MAXIMO,ALERTA_ESTADO,GRUPO) " +
        "VALUES (?,?,?,?,?,?,?,?)",
        "Producto resumen",
        "Prueba",
        1,
        "unidad",
        5,
        10,
        "NORMAL",
        "COCINA"
    );

    mvc.perform(post("/api/inventario/enviar")
            .session(owner)
            .contentType("application/json")
            .content("""
                {"group":"COCINA"}
                """))
        .andExpect(status().isOk())
        .andExpect(jsonPath("$.sent").value(true))
        .andExpect(jsonPath("$.count").value(1));

    assertEquals(
        3,
        jdbc.queryForObject(
            "SELECT COUNT(*) FROM APP_NOTIFICACION " +
            "WHERE MODULO='Inventario'",
            Integer.class
        )
    );

    assertEquals(
        1,
        jdbc.queryForObject(
            "SELECT COUNT(DISTINCT DETALLE) FROM APP_NOTIFICACION " +
            "WHERE MODULO='Inventario'",
            Integer.class
        )
    );
}
    @Test void notificationPreferencesAndDeliveryArePersonalAndDurable() throws Exception {
        org.mockito.Mockito.when(transport.mailReady()).thenReturn(true);
        preferences.save(2,new NotificationPreferences.Preferences(false,false,true,"worker@example.test"));
        notifications.employee(2,"Tareas diarias","Tarea: Preparar. Fecha: 2026-10-01. Área: COCINA");
        mvc.perform(get("/api/notificaciones").session(worker)).andExpect(jsonPath("$.unread").value(0));
        mvc.perform(get("/api/notificaciones/preferencias").session(otherWorker)).andExpect(jsonPath("$.internal").value(true)).andExpect(jsonPath("$.mail").value(false));
        assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM APP_NOTIF_ENVIO WHERE ESTADO='PENDIENTE'",Integer.class));
        delivery.deliver();delivery.deliver();
        org.mockito.Mockito.verify(transport,org.mockito.Mockito.times(1)).mail(org.mockito.ArgumentMatchers.eq("worker@example.test"),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.eq("Tareas diarias"),org.mockito.ArgumentMatchers.contains("Fecha:"));
        mvc.perform(put("/api/notificaciones/preferencias").session(worker).contentType("application/json").content("{\"internal\":true,\"push\":false,\"mail\":false,\"email\":\"\",\"userId\":1}"))
            .andExpect(status().isOk());
        assertTrue(preferences.get(1).internal());assertFalse(preferences.get(1).mail());
        mvc.perform(put("/api/notificaciones/preferencias").session(worker).contentType("application/json").content("{\"mail\":true,\"email\":\"bad\"}"))
            .andExpect(status().isBadRequest());
    }
    @Test void pushExpiredSubscriptionsAreRemovedAndTransientErrorsRetry() throws Exception {
        org.mockito.Mockito.when(transport.pushReady()).thenReturn(true);
        preferences.save(2,new NotificationPreferences.Preferences(true,true,false,""));
        jdbc.update("INSERT INTO APP_PUSH_SUSCRIPCION(ID_USUARIO,ENDPOINT,ENDPOINT_HASH,P256DH,AUTH) VALUES(2,'https://fcm.googleapis.com/wp/test','test','key','auth')");
        notifications.employee(2,"Horarios","Nuevo horario");
        org.mockito.Mockito.when(transport.push(org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString())).thenReturn(503);
        delivery.deliver();
        assertEquals(1,jdbc.queryForObject("SELECT INTENTOS FROM APP_NOTIF_ENVIO",Integer.class));
        jdbc.update("UPDATE APP_NOTIF_ENVIO SET PROXIMO_INTENTO=SYSTIMESTAMP");
        org.mockito.Mockito.when(transport.push(org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString())).thenReturn(410);
        delivery.deliver();
        assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM APP_PUSH_SUSCRIPCION",Integer.class));
        assertEquals("OMITIDO",jdbc.queryForObject("SELECT ESTADO FROM APP_NOTIF_ENVIO",String.class));
        for(String endpoint:new String[]{"http://127.0.0.1/","https://evil.test/","https://fcm.googleapis.com.evil.test/","https://user@fcm.googleapis.com/","https://fcm.googleapis.com:123/"})
            assertThrows(IllegalArgumentException.class,()->PushSubscriptions.validateEndpoint(endpoint));
    }

}
