-- Ejecutar como SCRIPT (F5) en Oracle Cloud, conectado como RESTAPI_HOY2609.
-- Para una instalación existente. NO ejecutar de nuevo APP_ESQUEMA.sql.
-- Cambios aditivos; no borra registros, cuentas ni tablas.
-- Oracle confirma DDL automáticamente. Conserva un respaldo antes de migrar.
-- El bloque valida el esquema y los prerrequisitos ANTES de modificarlo.
SET SERVEROUTPUT ON;
DECLARE
    n NUMBER;
    PROCEDURE ensure_table(table_name_in VARCHAR2, ddl VARCHAR2) IS
        found NUMBER;
    BEGIN
        SELECT COUNT(*) INTO found FROM user_tables WHERE table_name=table_name_in;
        IF found=0 THEN EXECUTE IMMEDIATE ddl; END IF;
    END;
BEGIN
    IF USER <> 'RESTAPI_HOY2609' THEN
        RAISE_APPLICATION_ERROR(-20001,'Conéctate como RESTAPI_HOY2609, no como ADMIN ni SYSTEM.');
    END IF;
    SELECT COUNT(*) INTO n FROM user_tables WHERE table_name IN
        ('APP_EMPLEADO','APP_USUARIO','APP_TAREA_DIARIA','APP_ACTIVIDAD','APP_EVIDENCIA_TAREA');
    IF n<>5 THEN RAISE_APPLICATION_ERROR(-20002,'Faltan tablas del proyecto original. Revisa la instalación antes de continuar.'); END IF;

    SELECT COUNT(*) INTO n FROM user_tab_columns WHERE table_name='APP_TAREA_DIARIA' AND column_name='AREA';
    IF n=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE APP_TAREA_DIARIA ADD (AREA VARCHAR2(80 CHAR))'; END IF;
    -- Solo clasifica tareas sin área cuando la ficha actual reconoce una de las cuatro áreas.
    -- Las demás quedan visibles para el administrador en "Clasificar tareas antiguas sin área".
    EXECUTE IMMEDIATE q'[
        UPDATE APP_TAREA_DIARIA T SET AREA=(
            SELECT TRANSLATE(UPPER(TRIM(E.AREA)),'ÁÉÍÓÚÜ','AEIOUU') FROM APP_EMPLEADO E
            WHERE E.ID_EMPLEADO=T.RESPONSABLE_ID)
        WHERE T.AREA IS NULL AND EXISTS (
            SELECT 1 FROM APP_EMPLEADO E WHERE E.ID_EMPLEADO=T.RESPONSABLE_ID
            AND TRANSLATE(UPPER(TRIM(E.AREA)),'ÁÉÍÓÚÜ','AEIOUU') IN ('COCINA','SALON','BARRA','COPERIA'))
    ]';
    COMMIT;
    SELECT COUNT(*) INTO n FROM user_constraints WHERE constraint_name='CK_APP_TAREA_AREA';
    IF n=0 THEN EXECUTE IMMEDIATE q'[ALTER TABLE APP_TAREA_DIARIA ADD CONSTRAINT CK_APP_TAREA_AREA CHECK (AREA IN ('COCINA','SALON','BARRA','COPERIA'))]'; END IF;
    SELECT COUNT(*) INTO n FROM user_indexes WHERE index_name='IX_APP_TAREA_AREA';
    IF n=0 THEN EXECUTE IMMEDIATE 'CREATE INDEX IX_APP_TAREA_AREA ON APP_TAREA_DIARIA (AREA, RESPONSABLE_ID)'; END IF;

    ensure_table('APP_PLAZA',q'[
        CREATE TABLE APP_PLAZA (
            ID_PLAZA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            CARGO VARCHAR2(80 CHAR) NOT NULL,
            AREA VARCHAR2(80 CHAR) NOT NULL,
            CUPOS NUMBER(4) NOT NULL,
            ACTIVA CHAR(1) DEFAULT 'S' NOT NULL,
            CREADO_EN TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT CK_APP_PLAZA_AREA CHECK (AREA IN ('COCINA','SALON','BARRA','COPERIA')),
            CONSTRAINT CK_APP_PLAZA_CUPOS CHECK (CUPOS BETWEEN 1 AND 9999),
            CONSTRAINT CK_APP_PLAZA_ACTIVA CHECK (ACTIVA IN ('S','N'))
        )
    ]');
    SELECT COUNT(*) INTO n FROM user_indexes WHERE index_name='UQ_APP_PLAZA_CARGO_AREA';
    IF n=0 THEN EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UQ_APP_PLAZA_CARGO_AREA ON APP_PLAZA (UPPER(TRIM(CARGO)), AREA)'; END IF;

    ensure_table('APP_HORARIO_IMAGEN',q'[
        CREATE TABLE APP_HORARIO_IMAGEN (
            ID_HORARIO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            TITULO VARCHAR2(160 CHAR) NOT NULL,
            NOMBRE_ARCHIVO VARCHAR2(255 CHAR) NOT NULL,
            TIPO_CONTENIDO VARCHAR2(80 CHAR) NOT NULL,
            IMAGEN BLOB NOT NULL,
            CREADO_POR NUMBER,
            CREADO_EN TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT FK_APP_HORARIO_AUTOR FOREIGN KEY (CREADO_POR)
                REFERENCES APP_USUARIO (ID_USUARIO) ON DELETE SET NULL,
            CONSTRAINT CK_APP_HORARIO_TIPO CHECK (TIPO_CONTENIDO IN ('image/jpeg','image/png','image/webp'))
        )
    ]');
    DBMS_OUTPUT.PUT_LINE('Migración terminada. No se cambiaron roles ni credenciales.');
END;
/

-- Verificación de solo lectura: las tablas nuevas deben aparecer.
SELECT table_name FROM user_tables WHERE table_name IN ('APP_PLAZA','APP_HORARIO_IMAGEN');
SELECT AREA, COUNT(*) AS TOTAL_TAREAS FROM APP_TAREA_DIARIA GROUP BY AREA;
